### ISSUE TITLE
Dependencies unavailable

### ISSUE THREAD

**Issue by GijsM** [InventivetalentDev/CompactNPCLib#12]
The bukkit & craftbukkit dependencies for this project are both 1.10 which is unavailable atm.

**Comment by InventivetalentDev** [comment]
Fixed in https://github.com/InventivetalentDev/CompactNPCLib/commit/5bb188e5a7b61d260899d0f75cc6756980b17f49 / https://github.com/InventivetalentDev/CompactNPCLib/commit/bd8b965b910a7fa59ce2ebb0df72a8fd3df2b112
