### ISSUE TITLE
NPC Create Error

### ISSUE THREAD

**Issue by pepsiisgross** [InventivetalentDev/CompactNPCLib#14]
## What steps will reproduce the problem?  
1. Use /cmdnpc create in-game.

## What were you expecting to happen? What happened instead?  
I was expecting for it to create an NPC, I got an error and no NPC instead.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
CommandNPCS version 1.2.4
NPCLib version 2.2.2
PacketListenerAPI version 3.4.4

## What Spigot version are you using? *Type /version*  
1.9.4-R0.1-SNAPSHOT

## What plugins are you using? *Type /plugins*  
Not needed?

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://hastebin.com/eciseyumip.rb

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm not using Bungeecord. Not testing in previous versions.

**Comment by InventivetalentDev** [comment]
This is not an issue with NPCLib, you are using an external plugin depending on it (CommandNPCs).
CommandNPCs is currently not compatible with the latest NPCLib version. Either wait for the update, or use a pre-2.0 version of NPCLib.
