### ISSUE TITLE
NPCPlayer#setBodyYaw() and NPCPlayer#setLaying() doesnt work

### ISSUE THREAD

**Issue by GPSforLEGENDS** [InventivetalentDev/CompactNPCLib#17]
## What steps will reproduce the problem?  
1. If you reload your server the following code doesnt work anymore.  
```java
@Override
	public void onEnable() {
		NPCLib.createRegistry(this);
	}
	@Override
	public boolean onCommand(CommandSender sender, Command command,
			String label, String[] args) {
		if(command.getName().equalsIgnoreCase("blabla")){
			Player p = (Player)sender;
			
                         NPCPlayer npc = NPCRegistry.getRegistry(this).spawnPlayerNPC(p.getLocation(), NPCPlayer.class, UUID.randomUUID(), ChatColor.GRAY + p.getName());
			npc.setPitch(90);
			npc.setBodyYaw(90);
```
2.  setLaying isnt working neither

3. 

## What were you expecting to happen? What happened instead?  

that player lays down or sets the body yaw. laying down still worked but it corrupts your world files.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

2.2.4

## What Spigot version are you using? *Type /version*  

[18:59:56] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  

NPCLib, packerlistenerapi, my custom plugin.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

Laying: http://pastebin.com/434N0T7q
setBodyYaw: http://pastebin.com/fs96ND3h

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well* 

no 

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

-

**Comment by InventivetalentDev** [comment]
Don't reload your server, pretty simple solution :)
