### ISSUE TITLE
NPCs are not influenced by gravity or velocity.

### ISSUE THREAD

**Issue by lizardfreak321** [InventivetalentDev/CompactNPCLib#19]
## What steps will reproduce the problem?  
1. Spawn a PlayerNPC
2. Try to push it
3. Make it have nothing to stand on so it floats.

## What were you expecting to happen? What happened instead?  
I expected it to move and fall, instead it just stayed there.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
2.2.4

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Plugins (13): WorldEdit, RollbackCore, speedmodifier, PacketListenerApi, ChatControl, custom, PlugMan, NametagEdit, Vault, NickNamer, NPCLib, custom, custom.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It is not behind bungeecord. It worked in the 1.x.x version of this plugin, and I cannot find a method to toggle this.

**Comment by InventivetalentDev** [comment]
Should be fixed in v2.2.5.

**Comment by joshcal22** [comment]
I have version 2.2.6 installed and I am having this issue
