### ISSUE TITLE
Craftbukkit dependency

### ISSUE THREAD

**Issue by toonsevrin** [InventivetalentDev/CompactNPCLib#24]
Should there be a craftbukkit 1.9.4 and 1.10.2 dependency in the pom.xml? If not, can these be removed?

**Comment by lizardfreak321** [comment]
It needs it for the NMS and CraftBukkit methods. This plugin uses NMS and CraftBukkit directly so we don't need to.

**Comment by InventivetalentDev** [comment]
Has been removed. (https://github.com/InventivetalentDev/CompactNPCLib/commit/1c562db0b839b6f06a9ed433ed27d71894e5b795)
