### ISSUE TITLE
it won't load

### ISSUE THREAD

**Issue by harry2512tea** [InventivetalentDev/CompactNPCLib#33]
## What steps will reproduce the problem?  
1. starting up the server
2. 
3. 

## What were you expecting to happen? What happened instead?  
i was expecting it to load up properly. it just doesn't recognise it.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
i have tried 1.8.6 and 2.2.6
## What Spigot version are you using? *Type /version*  
1.8.8 spigot   git-spigot-e4d4710-e1ebe52
## What plugins are you using? *Type /plugins*  
permissionsEX antimcleaks resourcepackapi worldedit nicknamer menubuilder silkspawners murder
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
no point because it doesn't show anything to do with it.
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
nothing went wrong, just won't load.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
i am using bungeecord, but i am only loading it on one server. it has never worked for me.

**Comment by InventivetalentDev** [comment]
Post the error log, please.

**Comment by harry2512tea** [comment]
there isn't one. the server just doesn't recognise that its even there

**Comment by lizardfreak321** [comment]
The server will show something in the server log unless it isn't a jar file type. Post your entire log if you are comfortable doing that, if you aren't, post cut out everything you don't want public.

**Comment by harry2512tea** [comment]
14.01 16:48:24 [Server] ERROR Could not load 'plugins/NPCLib_v1.8.6.jar' in folder 'plugins'
that is all it says about it

**Comment by harry2512tea** [comment]
it's the same for version 2.2.6

**Comment by harry2512tea** [comment]
here is the entire log: http://pastebin.com/E9rRRevA

**Comment by lizardfreak321** [comment]
INFO org.bukkit.plugin.UnknownDependencyException: PacketListenerApi

That's the problem.

**Comment by harry2512tea** [comment]
how can i fix it?

**Comment by lizardfreak321** [comment]
You install PacketListenerAPI

**Comment by harry2512tea** [comment]
ah, thank you. i'll reply to say if it works or not

**Comment by harry2512tea** [comment]
it worked!! thank you so much!

**Comment by lizardfreak321** [comment]
No problem. I think installation instructions should be added to the plugin page.

**Comment by harry2512tea** [comment]
probably, quite a few people have had the same problem as me

**Comment by harry2512tea** [comment]
once again, thanks.

**Comment by InventivetalentDev** [comment]
![...](https://i.inventivetalent.org/2017/01/14/c47b0d0c5f_chrome.png)  
Isn't that kinda obvious? Just read the full page before downloading something.

**Comment by lizardfreak321** [comment]
It is, just not for anyone who isn't familiar with dependencies.
