### ISSUE TITLE
THIS PLUGIN NOT WORKING WITH MURDER

### ISSUE THREAD

**Issue by tapiero** [InventivetalentDev/CompactNPCLib#40]
I started the version of spigot 1.8 with this plugin: menu builder 1.1.0, murder 3.3.1, nicknamer 3.13.3, npclib 2.5.0, packet listener api 3.6.0, resourcepack api 2.2.1. in the console I always get error messages with npc lib. how should I do it?

Murder: https://www.spigotmc.org/resources/murder.1052/

**Comment by InventivetalentDev** [comment]
Too much caps.
