### ISSUE TITLE
 This plugin depends on NPCLib

### ISSUE THREAD

**Issue by cat5555** [InventivetalentDev/CompactNPCLib#43]
## What steps will reproduce the problem?  
1. Download NPCLib From GitHub
2. Put NPCLibs 2.5.0-SNAPSHOT .jar in plugins
3. And start server (1GB_RAM_START.bat)

## What were you expecting to happen? What happened instead?  
plugin murder mysters start. [19:43:55] [Server thread/INFO]: [Murder] Disabling Murder v3.3.1-SNAPSHOT
[19:43:55] [Server thread/INFO]: [Murder] Saving data...
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NPCLibs 2.5.0-SNAPSHOT .jar and api-2.5.0-SNAPSHOT.jar
## What Spigot version are you using? *Type /version*  
1.10
## What plugins are you using? *Type /plugins*  
MenuBuilder_v1.1.0-SNAPSHOT.jar, ResourcePackAPI_v2.2.1.jar, NickNamer_v3.13.3-SNAPSHOT.jar, Murder_v3.3.1-SNAPSHOT.jar
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/g4QdeiKX
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No.

**Comment by Sprax2013** [comment]
The log says all you need:

> Could not load 'plugins\api-2.5.0-SNAPSHOT.jar' in folder 'plugins'
> [...] Invalid plugin.yml
> [...] Jar does not contain plugin.yml

> Could not load 'plugins\NPCLib_v2.5.0-SNAPSHOT.jar' in folder 'plugins'
> [...] UnknownDependencyException: PacketListenerApi

On the Spigot-Page (https://www.spigotmc.org/resources/api-npclib.5853/) it says: 

> Depends on PacketListenerAPI

**Comment by InventivetalentDev** [comment]
Belongs to the Murder issue tracker. The dependency in the Murder plugin is to an earlier implementation of NPCLib (1.x).
