### ISSUE TITLE
How to use the method: NPCPlayer.setSkinTexture(String value, String signature)？

### ISSUE THREAD

**Issue by byxiaobai** [InventivetalentDev/CompactNPCLib#44]
I can't understand the "value" and "signature" means

**Comment by InventivetalentDev** [comment]
You can get both from e.g. https://mineskin.org/

**Comment by byxiaobai** [comment]
However, the resolution of the image obtained from that website is too low.Is there a higher resolution method?

**Comment by InventivetalentDev** [comment]
No. The resolution is limited by Minecraft to 64x64 pixels at most.

**Comment by byxiaobai** [comment]
thanks!
